### ISSUE TITLE
How TRGT determine whether TR is homozygous or heterozygous for a diploid sample?

### ISSUE THREAD

**Issue by PengJia6** [PacificBiosciences/trgt#13]
Thank you for developing such an excellent tool.
When analyzing the human genome with TRGT, TRGT will filter out any cluster containing fewer than 10% of the total number of spanning reads. Afterward, does it select the two largest clusters as the two alleles?

Best，
Peng

**Comment by egor-dolzhenko** [comment]
Hi Peng. Thank you for the question! Yes, very roughly this is how the genotyper would work. The latest version of TRGT (to be released next week) also incorporates SNPs flanking the repeat into the genotyping process. Please let me know if you need any additional information. If you need assistance with reviewing any specific calls made by TRGT, please feel free to also reach out by [email](mailto:edolzhenko@pacificbiosciences.com).

Best wishes,
Egor

**Comment by PengJia6** [comment]
Hi Egor！ Thank you for your response. I'm revisiting the TRGT manuscript, and I'm just a bit puzzled. If a TR is homozygous, is it reasonable to select the top two clusters, or should the top cluster be chosen instead?

**Comment by egor-dolzhenko** [comment]
Ah, I see. Yes, here is what commonly happens for homozygous repeats: one cluster would be very large while the other cluster, if any, would contain only a small fraction of reads (usually much less than 10%). So only one cluster would remain after all the filtering is done.

We have also created a fully probabilistic version of this algorithm, but we have not incorporated it into TRGT yet since the small gain in accuracy does not seem to justify the increased runtime. We will add a description of this algorithm to TRGT docs once we sufficiently improve it and incorporate it into the program.

Did I answer your question? Please let me know if there is anything else you'd like to know.

**Comment by PengJia6** [comment]
Thank you for your very clear response!
